Removed dependence from daspanel/alpine-base.

diff --git a/rootfs/etc/cont-init.d/50-00-caddy b/rootfs/etc/cont-init.d/50-00-caddy
--- a/rootfs/etc/cont-init.d/50-00-caddy
+++ b/rootfs/etc/cont-init.d/50-00-caddy
@@ -1,25 +1,26 @@
 #!/usr/bin/with-contenv sh
 
+export DASPANEL_CONTAINER_TYPE="engine-static"
+printf $DASPANEL_CONTAINER_TYPE > /var/run/s6/container_environment/DASPANEL_CONTAINER_TYPE
+
 # Installation UUID must be informed
 if [ -z "$DASPANEL_SYS_UUID" ]; then
-    echo "***"
-    echo "ERROR: You must set the env variable DASPANEL_SYS_UUID to a valid UUID"
-    echo "***"
+    echo "[DASPANEL-$DASPANEL_CONTAINER_TYPE] ERROR: You must set the env variable DASPANEL_SYS_UUID to a valid UUID"
     exit 1
 fi
 
 case "$DASPANEL_WAIT_FOR_API" in
     YES|yes|Yes)
-        echo "[DASPANEL] Waiting 60 seconds for API: $0" >&2
+        echo "[DASPANEL-$DASPANEL_CONTAINER_TYPE] Waiting 60 seconds for API: $0" >&2
         /opt/daspanel/bin/wait-for-api -t 60 $DASPANEL_SYS_APISERVER/info/status
         result=$?
         if [ ! $result -eq 0 ] ; then
-            echo "[DASPANEL] Can not connect to API: $DASPANEL_SYS_APISERVER/info/status" >&2
+            echo "[DASPANEL-$DASPANEL_CONTAINER_TYPE] Can not connect to API: $DASPANEL_SYS_APISERVER/info/status" >&2
             exit 1
         fi
         ;;
     *) 
-        echo "[DASPANEL] Container not need to wait API become online: $0" >&2
+        echo "[DASPANEL-$DASPANEL_CONTAINER_TYPE] Container not need to wait API become online: $0" >&2
         exit 1
         ;;
 esac
@@ -28,10 +29,10 @@ esac
 SYSCFG=$(wget -O- --header=Content-Type:application/json --header="Authorization: $DASPANEL_SYS_APIKEY" "$DASPANEL_SYS_APISERVER/tenants/$DASPANEL_SYS_UUID")
 result=$?
 if [ ! $result -eq 0 ] ; then
-    echo "[DASPANEL] Unable to get tenant configuration from API server: $0" >&2
+    echo "[DASPANEL-$DASPANEL_CONTAINER_TYPE] Unable to get tenant configuration from API server: $0" >&2
     exit 1
 fi
-export DASPANEL_SYS_HOSTNAME=`echo $SYSCFG | /usr/bin/jq -r '.sys.hostname'`
+export DASPANEL_SYS_HOSTNAME=`echo $SYSCFG | /opt/daspanel/bin/jq -r '.sys.hostname'`
 export ENGINE="static"
 
 if [ ! -d "/etc/caddy" ]; then
@@ -45,15 +46,14 @@ if [ ! -d "/etc/caddy/sites-enabled" ]; then
 fi
 
 # Configure caddy
-/usr/bin/gomplate -d cfg=$DASPANEL_SYS_APISERVER/tenants/$DASPANEL_SYS_UUID \
+/opt/daspanel/bin/gomplate -d cfg=$DASPANEL_SYS_APISERVER/tenants/$DASPANEL_SYS_UUID \
     -H "cfg=Authorization: $DASPANEL_SYS_APIKEY" \
-    < /opt/daspanel/conf-templates/engine-static/caddy/caddyfile.tmpl \
+    < /opt/daspanel/conf-templates/$DASPANEL_CONTAINER_TYPE/caddy/caddyfile.tmpl \
     > /etc/caddy/caddyfile
 
 # Get sites http entries
-/opt/daspanel/bin/engine-static/daspanel.sites.sh
+/opt/daspanel/bin/$DASPANEL_CONTAINER_TYPE/daspanel.sites.sh
 
 # secure daspanel
 chown -R daspanel:daspanel /opt/daspanel/data
 chown -R daspanel:daspanel /opt/daspanel/log
-
