Initialization of the container using settings obtained from the API server.

diff --git a/rootfs/etc/cont-init.d/50-00-caddy b/rootfs/etc/cont-init.d/50-00-caddy
--- a/rootfs/etc/cont-init.d/50-00-caddy
+++ b/rootfs/etc/cont-init.d/50-00-caddy
@@ -8,6 +8,32 @@ if [ -z "$DASPANEL_SYS_UUID" ]; then
     exit 1
 fi
 
+case "$DASPANEL_WAIT_FOR_API" in
+    YES|yes|Yes)
+        echo "[DASPANEL] Waiting 60 seconds for API: $0" >&2
+        /opt/daspanel/bin/wait-for-api -t 60 $DASPANEL_SYS_APISERVER/info/status
+        result=$?
+        if [ ! $result -eq 0 ] ; then
+            echo "[DASPANEL] Can not connect to API: $DASPANEL_SYS_APISERVER/info/status" >&2
+            exit 1
+        fi
+        ;;
+    *) 
+        echo "[DASPANEL] Container not need to wait API become online: $0" >&2
+        exit 1
+        ;;
+esac
+
+# Get system configs from API server and set env variables
+SYSCFG=$(wget -O- --header=Content-Type:application/json --header="Authorization: $DASPANEL_SYS_APIKEY" "$DASPANEL_SYS_APISERVER/tenants/$DASPANEL_SYS_UUID")
+result=$?
+if [ ! $result -eq 0 ] ; then
+    echo "[DASPANEL] Unable to get tenant configuration from API server: $0" >&2
+    exit 1
+fi
+export DASPANEL_SYS_HOSTNAME=`echo $SYSCFG | /usr/bin/jq -r '.sys.hostname'`
+export ENGINE="static"
+
 if [ ! -d "/etc/caddy" ]; then
     mkdir -p /etc/caddy
 fi
@@ -18,17 +44,14 @@ if [ ! -d "/etc/caddy/sites-enabled" ]; then
     mkdir -p /etc/caddy/sites-enabled
 fi
 
-export DASPANEL_SYS_HOSTNAME=`cat /opt/daspanel/data/$DASPANEL_SYS_UUID/db/sysconfig.json | /usr/bin/jq -r '.sys.hostname'`
-export DASPANEL_SYS_APISERVER=`cat /opt/daspanel/data/$DASPANEL_SYS_UUID/db/sysconfig.json | /usr/bin/jq -r '.sys.apiserver'`
-
 # Configure caddy
-/usr/bin/gomplate -d cfg=file:///opt/daspanel/data/$DASPANEL_SYS_UUID/db/sysconfig.json \
-  < /opt/daspanel/conf-templates/engine-static/caddy/caddyfile.tmpl \
-  > /etc/caddy/caddyfile
+/usr/bin/gomplate -d cfg=$DASPANEL_SYS_APISERVER/tenants/$DASPANEL_SYS_UUID \
+    -H "cfg=Authorization: $DASPANEL_SYS_APIKEY" \
+    < /opt/daspanel/conf-templates/engine-static/caddy/caddyfile.tmpl \
+    > /etc/caddy/caddyfile
 
 # Get sites http entries
-export DASPANEL_HTTP_ENGINE="static"
-/usr/sbin/daspanel.sites.sh
+/opt/daspanel/bin/engine-static/daspanel.sites.sh
 
 # secure daspanel
 chown -R daspanel:daspanel /opt/daspanel/data
